---
title: "Homework" 
output: github_document
---

- Homework assignments are due by 4 p.m. on the due date unless otherwise specified. 

- Unexcused late homework will not be accepted

Assignment |Due Date | Solution
-----|---------|--------
[hw12](hw12.pdf) | 19-Nov |  
[hw11](hw11.pdf) | 04-Nov |  [soln-hw11](soln-hw11.pdf)
[hw10](hw10.pdf) | 01-Nov |  [soln-hw10](soln-hw10.pdf)
[hw09](hw09.pdf) | 29-Oct |  [soln-hw09](soln-hw09.pdf)
[hw08](hw08.pdf) | 25-Oct |  [soln-hw08](soln-hw08.pdf)
[hw07](hw07.pdf) | 11-Oct |  [soln-hw07](soln-hw07.pdf)
[hw06](hw06.pdf) | 08-Oct |  [soln-hw06](soln-hw06.pdf)
[hw05](hw05.pdf) | 04-Oct |  [soln-hw05](soln-hw05.pdf)
[hw04](hw04.pdf) | 01-Oct |  [soln-hw04](soln-hw04.pdf)
[hw03](hw03.pdf) | 27-Sep |  [soln-hw03](soln-hw03.pdf)
[hw02](hw02.pdf) | 24-Sep |  [soln-hw02](soln-hw02.pdf)
[hw01](hw01.pdf) | 20-Sep |  [soln-hw01](soln-hw01.pdf)



### Grading

Homework assignments will be graded out of 5 points, which are based on a combination of accuracy and effort. Below are rough guidelines for grading.

Grade | Description
------|------------------------------
5 |	All problems completed with detailed solutions provided and 75% or more of the problems are fully correct.
4 |	All problems completed with detailed solutions and 50-75% correct; OR close to all problems completed and 75%-100% correct. One point will be deducted if superfluous information is printed or if assignment is excessively long – ask me if you want clarification on "excessively long."
3	| Close to all problems completed with less than 75% correct.
2	| More than half but fewer than all problems completed and at least 75% correct
1	| More than half but fewer than all problems completed and less than 75% correct; OR less than half of problems completed
0	| No work submitted, OR half or less than half of the problems submitted and without any detail/work shown to explain the solutions.